default_language_version:
  python: python3
fail_fast: true
repos:
  - repo: https://github.com/ambv/black
    rev: 193ee766ca496871f93621d6b58d57a6564ff81b  # frozen: 23.7.0
    hooks:
    - id: black
