# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("aws_tools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebssnapshot",
            name="ebs_volume",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="aws_tools.EBSVolume"),
        ),
        migrations.AlterField(
            model_name="ebsvolume",
            name="instance",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="aws_tools.Instance"
            ),
        ),
    ]
