# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aws_tools", "0008_ebssnapshot_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebsvolume",
            name="present",
            field=models.BooleanField(default=True),
        ),
    ]
