# Generated by Django 2.1.5 on 2019-01-09 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aws_tools", "0016_securitygrouprule_securitygroupruleiprange_securitygroupruleusergrouppair"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ebssnapshot",
            options={"get_latest_by": "created_at", "ordering": ["-created_at"]},
        ),
    ]
