# Generated by Django 2.1.5 on 2019-01-21 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aws_tools", "0018_awsorganization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awsorganization",
            name="region_name",
        ),
    ]
