# Generated by Django 2.1.5 on 2019-01-21 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aws_tools", "0019_remove_awsorganization_region_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="awsaccount",
            old_name="role_arn",
            new_name="_role_arn",
        ),
    ]
