# Generated by Django 3.0.6 on 2020-05-16 13:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations
from backend.aws_tools.helpers import default_schedule


class Migration(migrations.Migration):
    dependencies = [
        ("aws_tools", "0036_auto_20200516_1236"),
    ]

    operations = [
        migrations.AddField(
            model_name="instanceschedule",
            name="days",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=default_schedule),
        ),
        migrations.DeleteModel(
            name="ScheduleDay",
        ),
    ]
