# Generated by Django 3.0.6 on 2020-06-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aws_tools", "0041_auto_20200517_1130"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="awsaccount",
            options={"verbose_name": "AWS Account"},
        ),
        migrations.AlterModelOptions(
            name="awsorganization",
            options={"verbose_name": "AWS Organization"},
        ),
        migrations.AlterModelOptions(
            name="awsregion",
            options={"verbose_name": "AWS Region"},
        ),
        migrations.AlterModelOptions(
            name="ebssnapshot",
            options={"get_latest_by": "created_at", "ordering": ["-created_at"], "verbose_name": "EBS Snapshot"},
        ),
        migrations.AlterModelOptions(
            name="ebsvolume",
            options={"verbose_name": "EBS Volume"},
        ),
        migrations.AlterField(
            model_name="instanceschedule",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
