# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_tools', '0013_auto_20170310_1542'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='ebssnapshot',
            order_with_respect_to=None,
        ),
    ]
