# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("aws_tools", "0007_ebsvolume_backup"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebssnapshot",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
