# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws_tools", "0011_auto_20170306_1657"),
    ]

    operations = [
        migrations.AddField(model_name="instance", name="backup", field=models.BooleanField(default=False),),
    ]
