# Generated by Django 2.2 on 2019-04-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_tools', '0028_auto_20190410_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitygroup',
            name='description',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
