# Generated by Django 3.0.6 on 2020-05-16 10:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import helpers


class Migration(migrations.Migration):

    dependencies = [
        ('aws_tools', '0035_securitygroup_vpc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='awsregion',
            name='name',
            field=models.CharField(choices=[('us-east-1', 'US East (N. Virginia)'), ('us-east-2', 'US East (Ohio)'), ('us-west-1', 'US West (N. California)'), ('us-west-2', 'US West (Oregon)'), ('ap-south-1', 'Asia Pacific (Mumbai)'), ('ap-northeast-2', 'Asia Pacific (Seoul)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('ap-southeast-2', 'Asia Pacific (Sydney)'), ('ap-northeast-1', 'Asia Pacific (Tokyo)'), ('eu-central-1', 'EU (Frankfurt)'), ('eu-west-1', 'EU (Ireland)'), ('eu-west-2', 'EU (London)'), ('eu-west-3', 'EU (Paris)'), ('sa-east-1', 'South America (São Paolo)')], max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='ebssnapshot',
            name='region_name',
            field=models.CharField(choices=[('us-east-1', 'US East (N. Virginia)'), ('us-east-2', 'US East (Ohio)'), ('us-west-1', 'US West (N. California)'), ('us-west-2', 'US West (Oregon)'), ('ap-south-1', 'Asia Pacific (Mumbai)'), ('ap-northeast-2', 'Asia Pacific (Seoul)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('ap-southeast-2', 'Asia Pacific (Sydney)'), ('ap-northeast-1', 'Asia Pacific (Tokyo)'), ('eu-central-1', 'EU (Frankfurt)'), ('eu-west-1', 'EU (Ireland)'), ('eu-west-2', 'EU (London)'), ('eu-west-3', 'EU (Paris)'), ('sa-east-1', 'South America (São Paolo)')], editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='ebsvolume',
            name='region_name',
            field=models.CharField(choices=[('us-east-1', 'US East (N. Virginia)'), ('us-east-2', 'US East (Ohio)'), ('us-west-1', 'US West (N. California)'), ('us-west-2', 'US West (Oregon)'), ('ap-south-1', 'Asia Pacific (Mumbai)'), ('ap-northeast-2', 'Asia Pacific (Seoul)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('ap-southeast-2', 'Asia Pacific (Sydney)'), ('ap-northeast-1', 'Asia Pacific (Tokyo)'), ('eu-central-1', 'EU (Frankfurt)'), ('eu-west-1', 'EU (Ireland)'), ('eu-west-2', 'EU (London)'), ('eu-west-3', 'EU (Paris)'), ('sa-east-1', 'South America (São Paolo)')], editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='instance',
            name='region_name',
            field=models.CharField(choices=[('us-east-1', 'US East (N. Virginia)'), ('us-east-2', 'US East (Ohio)'), ('us-west-1', 'US West (N. California)'), ('us-west-2', 'US West (Oregon)'), ('ap-south-1', 'Asia Pacific (Mumbai)'), ('ap-northeast-2', 'Asia Pacific (Seoul)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('ap-southeast-2', 'Asia Pacific (Sydney)'), ('ap-northeast-1', 'Asia Pacific (Tokyo)'), ('eu-central-1', 'EU (Frankfurt)'), ('eu-west-1', 'EU (Ireland)'), ('eu-west-2', 'EU (London)'), ('eu-west-3', 'EU (Paris)'), ('sa-east-1', 'South America (São Paolo)')], editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='securitygroup',
            name='region_name',
            field=models.CharField(choices=[('us-east-1', 'US East (N. Virginia)'), ('us-east-2', 'US East (Ohio)'), ('us-west-1', 'US West (N. California)'), ('us-west-2', 'US West (Oregon)'), ('ap-south-1', 'Asia Pacific (Mumbai)'), ('ap-northeast-2', 'Asia Pacific (Seoul)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('ap-southeast-2', 'Asia Pacific (Sydney)'), ('ap-northeast-1', 'Asia Pacific (Tokyo)'), ('eu-central-1', 'EU (Frankfurt)'), ('eu-west-1', 'EU (Ireland)'), ('eu-west-2', 'EU (London)'), ('eu-west-3', 'EU (Paris)'), ('sa-east-1', 'South America (São Paolo)')], editable=False, max_length=25),
        ),
        migrations.AddField(
            model_name='instance',
            name='schedule',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='aws_tools.InstanceSchedule'),
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('day_schedule', django.contrib.postgres.fields.jsonb.JSONField(default=helpers.default_schedule)),
                ('schedule', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aws_tools.InstanceSchedule')),
            ],
            options={
                'unique_together': {('day', 'schedule')},
            },
        ),
    ]
