# Generated by Django 3.0.6 on 2020-05-17 08:36

import django.contrib.postgres.fields
from django.db import migrations, models
import helpers


class Migration(migrations.Migration):

    dependencies = [
        ('aws_tools', '0038_auto_20200516_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanceschedule',
            name='schedule',
        ),
        migrations.AddField(
            model_name='instanceschedule',
            name='sched',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'nothing'), (1, 'turn on'), (2, 'turn off')]), default=helpers.default_schedule, size=None, validators=[helpers.validate_schedule]),
        ),
    ]
