# Generated by Django 3.0.6 on 2020-06-10 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws_tools', '0042_auto_20200602_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDSInstance',
            fields=[
                ('_name', models.CharField(blank=True, max_length=100)),
                ('present', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('engine', models.CharField(editable=False, max_length=255)),
                ('engine_version', models.CharField(editable=False, max_length=255)),
                ('multi_az', models.BooleanField(editable=False)),
                ('aws_account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aws_tools.AWSAccount')),
                ('region', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aws_tools.AWSRegion')),
            ],
            options={
                'verbose_name': 'RDS Server',
                'abstract': False,
                'unique_together': {('_name', 'aws_account', 'region')},
            },
        ),
        migrations.CreateModel(
            name='RDSCluster',
            fields=[
                ('_name', models.CharField(blank=True, max_length=100)),
                ('present', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('engine', models.CharField(editable=False, max_length=255)),
                ('engine_version', models.CharField(editable=False, max_length=255)),
                ('multi_az', models.BooleanField(editable=False)),
                ('aws_account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aws_tools.AWSAccount')),
                ('region', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aws_tools.AWSRegion')),
            ],
            options={
                'verbose_name': 'RDS Server',
                'abstract': False,
                'unique_together': {('_name', 'aws_account', 'region')},
            },
        ),
    ]
