# Generated by Django 3.0.7 on 2020-06-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws_tools', '0043_auto_20200610_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rdscluster',
            options={'verbose_name': 'RDS Cluster'},
        ),
        migrations.AlterModelOptions(
            name='rdsinstance',
            options={'verbose_name': 'RDS Instance'},
        ),
        migrations.AddField(
            model_name='instanceschedule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rdscluster',
            name='schedule',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='aws_tools.InstanceSchedule'),
        ),
        migrations.AddField(
            model_name='rdsinstance',
            name='schedule',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='aws_tools.InstanceSchedule'),
        ),
        migrations.AlterUniqueTogether(
            name='rdscluster',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rdsinstance',
            unique_together=set(),
        ),
    ]
